In [3]:
import pandas as pd
dataframe = pd.read_csv(r"E:\Projects\gen-ai-log-classification\training\dataset\synthetic_logs.csv")
dataframe.head()

,timestamp,source,log_message,target_label
0,27-06-2025 07:20,ModernCRM,nova.osapi_compute.wsgi.server [req-b9718cd8-f...,HTTP Status
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error
2,1/17/2025 1:29,AnalyticsEngine,Unauthorized access to data was attempted,Security Alert
3,12-07-2025 00:24,ModernHR,nova.osapi_compute.wsgi.server [req-4895c258-b...,HTTP Status
4,02-06-2025 18:25,BillingSystem,nova.osapi_compute.wsgi.server [req-ee8bc8ba-9...,HTTP Status

In [4]:
dataframe.source.unique()

array(['ModernCRM', 'AnalyticsEngine', 'ModernHR', 'BillingSystem',
       'ThirdPartyAPI', 'LegacyCRM'], dtype=object)

In [5]:
dataframe.target_label.unique()

array(['HTTP Status', 'Critical Error', 'Security Alert', 'Error',
       'System Notification', 'Resource Usage', 'User Action',
       'Workflow Error', 'Deprecation Warning'], dtype=object)

In [ ]:
from sentence_transformers import SentenceTransformer
from sklearn.cluster import DBSCAN

# load pretrained
model = SentenceTransformer("all-MiniLM-L6-v2")

# generate embeddings
embeddings = model.encode(dataframe["log_message"])
embeddings.shape

(2410, 384)

In [26]:
# perform dbscan clustering
dbscan = DBSCAN(eps=0.2, min_samples=5, metric="euclidean")
clusters = dbscan.fit_predict(embeddings)

dataframe["cluster"] = clusters
dataframe.head()

,timestamp,source,log_message,target_label,cluster
0,27-06-2025 07:20,ModernCRM,nova.osapi_compute.wsgi.server [req-b9718cd8-f...,HTTP Status,0
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error,-1
2,1/17/2025 1:29,AnalyticsEngine,Unauthorized access to data was attempted,Security Alert,-1
3,12-07-2025 00:24,ModernHR,nova.osapi_compute.wsgi.server [req-4895c258-b...,HTTP Status,0
4,02-06-2025 18:25,BillingSystem,nova.osapi_compute.wsgi.server [req-ee8bc8ba-9...,HTTP Status,1

In [27]:
dataframe["cluster"].unique()

array([ 0, -1,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
       16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [28]:
dataframe[dataframe.cluster == 1].head()

,timestamp,source,log_message,target_label,cluster
4,02-06-2025 18:25,BillingSystem,nova.osapi_compute.wsgi.server [req-ee8bc8ba-9...,HTTP Status,1
9,30-03-2025 04:01,ModernHR,nova.osapi_compute.wsgi.server [req-2bf7cfee-a...,HTTP Status,1
17,27-01-2025 12:39,ModernCRM,nova.osapi_compute.wsgi.server [req-5f1c2027-e...,HTTP Status,1
24,16-12-2025 23:18,ModernCRM,nova.osapi_compute.wsgi.server [req-4e83daf7-a...,HTTP Status,1
33,06-10-2025 14:26,AnalyticsEngine,nova.osapi_compute.wsgi.server [req-fe9ef402-d...,HTTP Status,1